# Generated by Django 5.0.4 on 2024-05-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOnTheMap',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_path', models.CharField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('message', models.CharField(blank=True, null=True)),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'point_on_the_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_photo_path', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
